---
- hosts: all
  gather_facts: no
  vars:
    ansible_user: ec2-user
  tasks:

    - name: Wait for SSH
      wait_for_connection:
        sleep: 5
        timeout: 300

    - name: Install Docker
      command: amazon-linux-extras install -y docker
      become: true

    - name: Install docker-compose
      pip: 
        name: docker-compose
        executable: pip3
        state: present
      become: false
    
    - name: Enable and start docker 
      service: 
        name: docker
        enabled: true
        state: started
      become: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: true
      become: true
    
    - name: Pull image from repository
      shell: docker pull ghcr.io/2000ghz/hello-terraform/hello-terraform
      become: true

    - name: Download docker-compose.yml to the machine
      command: wget https://raw.githubusercontent.com/2000GHz/hello-terraform/main/docker-compose.yml

    - name: Copy binary to /usr/bin/
      command: cp /home/ec2-user/.local/bin/docker-compose /usr/bin
      become: true

    - name: Install Docker-Compose plugin
      shell: |
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        mkdir -p $DOCKER_CONFIG/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

    - name: Run container
      command: 'docker-compose up -d'
      register: command_output

    - debug:
        var: command_output.stdout_lines

      
    - name: Print IP address to access game
      command: echo 'The game is up and running at http://'
