---
- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for_connection:
        delay: 60
        sleep: 5
        timeout: 300

    - name: Install Docker
      ansible.builtin.yum:
        name: docker
        state: present
      become: true

    - name: Install docker-compose
      ansible.builtin.command: pip install docker-compose
      become: false
    
    - name: Pull image from repository
      ansible.builtin.command: docker pull ghcr.io/2000ghz/hello-terraform/hello-terraform
    
    - name: Run container
      ansible.builtin.command: docker run -td --rm -p 80:80 ghcr.io/2000ghz/hello-terraform/hello-terraform

    
