---
- hosts: all
  gather_facts: no
  vars:
    ansible_user: ec2-user
  tasks:

    - name: Wait for SSH
      wait_for_connection:
        sleep: 5
        timeout: 300

    - name: Install Docker
      command: amazon-linux-extras install -y docker
      become: true

    - name: Install docker-compose
      pip: 
        name: docker-compose
        executable: pip3
        state: present
      become: true
    
    - name: Enable and start docker 
      service: 
        name: docker
        enabled: true
        state: started
      become: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: true
      become: true
    
    - name: Pull image from repository
      shell: docker pull ghcr.io/2000ghz/hello-terraform/hello-terraform
      become: true

    - name: Transfer docker-compose.yml to the machine
      copy:
        src: /home/trabajo/Desktop/LucaTIC/hello-terraform/docker-compose.yml
        dest: /home/ec2-user/

    - name: Run container
      shell: '/usr/local/bin/docker-compose up -d'
      become: true

    - debug:
        msg: "The game is up and running at http://{{ ansible_host }} "
        
