---
- hosts: all
  vars:
    ansible_user: ec2-user
  tasks:

    - name: Wait for SSH
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300

    - name: Install Docker
      command: amazon-linux-extras install -y docker
      become: true

    - name: Install docker-compose
      pip: 
        name: docker-compose
        executable: pip3
      become: false
    
    - name: Enable and start docker 
      service: 
        name: docker
        enabled: true
        state: started
      become: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: true
      become: true
    
    - name: Pull image from repository
      shell: docker pull ghcr.io/2000ghz/hello-terraform/hello-terraform
      become: true

    - name: Download docker-compose.yml to the machine
      command: wget https://raw.githubusercontent.com/2000GHz/hello-terraform/main/docker-compose.yml
    
    - name: Wait for the file to be downloaded
      wait_for:
        path: ~/docker-compose.yml
        state: present

    - name: Run container
      command: ~/.local/bin/docker-compose up -d
      become: true
    
