---
- hosts: all
  vars:
    ansible_user: ec2-user
  tasks:

    - name: Wait for SSH
      wait_for_connection:
        delay: 60
        sleep: 5
        timeout: 300

    - name: Install Docker
      command: amazon-linux-extras install -y docker
      become: true

    - name: Install docker-compose
      pip: 
        name: docker-compose
        executable: pip3
      become: false
    
    - name: Enable and start docker 
      service: 
        name: docker
        enabled: true
        state: started
      become: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: true
      become: true
    
    - name: Pull image from repository
      shell: docker pull ghcr.io/2000ghz/hello-terraform/hello-terraform

    - name: Copy docker-compose.yml to the machine
      copy:
        src: "/home/trabajo/Desktop/LucaTIC/hello-terraform"
        dest: "/home/ec2-user"
        owner: ec2-user
        group: ec2-user
        mode: '0644'
        directory_mode: '0755'
    
    - name: Run container
      command: docker-compose -f ~/docker-compose.yml up -d
      become: false
    
