---
- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for_connection:
        delay: 30
        sleep: 5
        timeout: 300

    - name: Install Docker
      command: amazon-linux-extras install -y docker
      become: true

    - name: Install docker-compose
      pip: 
        name: docker-compose 
      become: false
    
    - name: Enable and start docker 
      service: 
        name: docker
        state: started

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: true
    
    - name: Pull image from repository
      shell: ~/.local/bin/docker-compose pull ghcr.io/2000ghz/hello-terraform/hello-terraform
    
    - name: Run container
      command: docker-compose up -d
    
